- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: update
    command : apt update -y

  - name : Install Docker
    command : apt install docker.io -y

  - name : Start Docker Service
    command : systemctl start docker

  - name: Deploy Docker Container
    command: docker run -it -p 8084:8081 docker pull venkat2528/bank-app:12
